version: "3.7"
services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3306:3306"
    volumes:
      - ./local-data:/var/lib/mysql
      - ./scripts/db-init:/docker-entrypoint-initdb.d